backend:
    name: git-gateway
    branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://ik.imagekit.io/betterwebsite/Britalbin/logo.svg?updatedAt=1743780308966

media_folder: "src/assets/images/blog"
public_folder: "/assets/images/blog"

collections:
    # Listings CONFIG
    # Paintings CONFIG (converted from file-based to folder-based collection)
    # Art Collections CONFIG
    - label: Art Collections
      name: artCollections
      delete: false
      editor:
        preview: false
      files:
        - label: Art Collections
          name: artCollections
          file: src/_data/Artcollections.json
          description: The art collections for the website.
          fields:
            - label: Collections
              name: collections
              label_singular: Collection
              widget: list
              fields:
                - label: Title
                  name: title
                  widget: string
                - label: Header Background
                  name: background
                  widget: image
                  required: false
                - label: Description Title
                  name: description_title
                  widget: string
                  required: false
                - label: Description
                  name: description
                  widget: markdown
                  required: false
                - label: Paintings
                  name: paintings
                  label_singular: Painting
                  widget: list
                  fields:
                    - label: Title
                      name: title
                      widget: string
                    - label: Feature Image
                      name: feature_image
                      widget: image
                    - label: Price
                      name: price
                      widget: number
                    - label: URL
                      name: url
                      widget: string
                      required: false