backend:
    name: git-gateway
    branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://codestitch.app/frontend/images/logo.png

media_folder: "src/assets/images/blog"
public_folder: "/assets/images/blog"

collections:
    - name: "blog"
      label: "Blog"
      folder: "src/content/blog"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
                label: "URL Slug",
                name: "url",
                widget: "string",
                hint: 'Specify where the page will be written to. If you use "Blog Post", the post will be accessible from "blog/blog-post"',
            }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
          - { label: "Featured Image", name: "image", widget: "image" }
          - { label: "Image Caption", name: "imageAlt", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
    # Listings CONFIG
    - label: Paintings
      name: paintings
      delete: false
      editor:
          preview: false
      files:
          - label: Listings
            name: listings
            file: src/_data/paintings.json
            description: The listings that exists on the /listings page
            fields:
                - label: Listings
                  name: listings
                  label_singular: Listing
                  widget: list
                  fields:

                      - label: Address
                        name: address
                        widget: string

                      - label: Listing Type
                        name: listing_type
                        widget: select
                        options: ["sale", "lease", "both", "sold"]
                        default: "sale"

                      - label: Featured Image
                        name: image
                        widget: image

                      - label: Buildings
                        name: buildings
                        label_singular: Building
                        widget: list
                        required: false
                        fields:
                          - label: Square Feet
                            name: square_feet
                            widget: number
                            value_type: "float"
                            required: false

                          - label: Lot Size (Acres)
                            name: lot_acres
                            widget: number
                            value_type: "float"
                            required: false

                          - label: Year Built
                            name: year_built
                            widget: number
                            required: false

                      
                      - label: Price
                        name: price
                        widget: object
                        required: false
                        fields:

                        - label: Sale Price
                          name: sale_price
                          widget: number
                          required: false
                          hint: 'Leave this blank for "Lease", use "Lease Rate" below instead'

                        - label: Lease Rate
                          name: lease_rate
                          widget: string
                          required: false
                          hint: 'Please format this with "$" and "/SF/Mo/Yr" example: $150/Sf/Mo'

                        - label: Price Per SF
                          name: price_per
                          widget: number
                          value_type: "float"
                          required: false

                      - label: Misc
                        name: misc
                        widget: object
                        required: false
                        fields:

                        - label: Traffic Count
                          name: taffic
                          widget: number
                          required: false

                        - label: Cap Rate
                          name: caprate
                          widget: number
                          value_type: "float"
                          required: false

                        - label: Zoning
                          name: zoning
                          widget: string
                          required: false

                        - label: Parcel ID
                          name: parcelid
                          widget: string
                          required: false

                      - label: Location
                        name: location
                        widget: object
                        fields:

                        - label: City
                          name: city
                          widget: string

                        - label: State
                          name: state
                          widget: string
                          default: 'OK'

                        - label: Zipcode
                          name: zipcode
                          widget: string

                        - label: Latitude
                          name: lat
                          widget: number
                          value_type: "float"

                        - label: Longitude
                          name: lng
                          widget: number
                          value_type: "float"

                      - label: Description
                        name: description
                        widget: markdown

                      - label: Agent Name
                        name: agent_name
                        widget: string

                      - label: Additional Images
                        name: additional_images
                        widget: image
                        required: false

                      - label: Additional Content
                        name: sections
                        label_singular: Section
                        widget: list
                        required: false
                        fields:
                            - label: Section Name
                              name: section_name
                              widget: string

                            - label: Section Description
                              name: section_description
                              widget: string
